# Generated by Django 3.1.2 on 2020-12-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.IntegerField(null=True),
        ),
    ]
